<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('tbcountries', function (Blueprint $table) {
            $table->string('idcountry', 10)->primary();
            $table->string('country_name', 100);
            $table->string('dial_code', 10);
        });
        $country = array(
            array("country_name" => "Afghanistan", "dial_code" => "+93", "idcountry" => "AF"),
            array("country_name" => "Aland Islands", "dial_code" => "+358", "idcountry" => "AX"),
            array("country_name" => "Albania", "dial_code" => "+355", "idcountry" => "AL"),
            array("country_name" => "Algeria", "dial_code" => "+213", "idcountry" => "DZ"),
            array("country_name" => "AmericanSamoa", "dial_code" => "+1684", "idcountry" => "AS"),
            array("country_name" => "Andorra", "dial_code" => "+376", "idcountry" => "AD"),
            array("country_name" => "Angola", "dial_code" => "+244", "idcountry" => "AO"),
            array("country_name" => "Anguilla", "dial_code" => "+1264", "idcountry" => "AI"),
            array("country_name" => "Antarctica", "dial_code" => "+672", "idcountry" => "AQ"),
            array("country_name" => "Antigua and Barbuda", "dial_code" => "+1268", "idcountry" => "AG"),
            array("country_name" => "Argentina", "dial_code" => "+54", "idcountry" => "AR"),
            array("country_name" => "Armenia", "dial_code" => "+374", "idcountry" => "AM"),
            array("country_name" => "Aruba", "dial_code" => "+297", "idcountry" => "AW"),
            array("country_name" => "Australia", "dial_code" => "+61", "idcountry" => "AU"),
            array("country_name" => "Austria", "dial_code" => "+43", "idcountry" => "AT"),
            array("country_name" => "Azerbaijan", "dial_code" => "+994", "idcountry" => "AZ"),
            array("country_name" => "Bahamas", "dial_code" => "+1242", "idcountry" => "BS"),
            array("country_name" => "Bahrain", "dial_code" => "+973", "idcountry" => "BH"),
            array("country_name" => "Bangladesh", "dial_code" => "+880", "idcountry" => "BD"),
            array("country_name" => "Barbados", "dial_code" => "+1246", "idcountry" => "BB"),
            array("country_name" => "Belarus", "dial_code" => "+375", "idcountry" => "BY"),
            array("country_name" => "Belgium", "dial_code" => "+32", "idcountry" => "BE"),
            array("country_name" => "Belize", "dial_code" => "+501", "idcountry" => "BZ"),
            array("country_name" => "Benin", "dial_code" => "+229", "idcountry" => "BJ"),
            array("country_name" => "Bermuda", "dial_code" => "+1441", "idcountry" => "BM"),
            array("country_name" => "Bhutan", "dial_code" => "+975", "idcountry" => "BT"),
            array("country_name" => "Bolivia, Plurinational State of", "dial_code" => "+591", "idcountry" => "BO"),
            array("country_name" => "Bosnia and Herzegovina", "dial_code" => "+387", "idcountry" => "BA"),
            array("country_name" => "Botswana", "dial_code" => "+267", "idcountry" => "BW"),
            array("country_name" => "Brazil", "dial_code" => "+55", "idcountry" => "BR"),
            array("country_name" => "British Indian Ocean Territory", "dial_code" => "+246", "idcountry" => "IO"),
            array("country_name" => "Brunei Darussalam", "dial_code" => "+673", "idcountry" => "BN"),
            array("country_name" => "Bulgaria", "dial_code" => "+359", "idcountry" => "BG"),
            array("country_name" => "Burkina Faso", "dial_code" => "+226", "idcountry" => "BF"),
            array("country_name" => "Burundi", "dial_code" => "+257", "idcountry" => "BI"),
            array("country_name" => "Cambodia", "dial_code" => "+855", "idcountry" => "KH"),
            array("country_name" => "Cameroon", "dial_code" => "+237", "idcountry" => "CM"),
            array("country_name" => "Canada", "dial_code" => "+1", "idcountry" => "CA"),
            array("country_name" => "Cape Verde", "dial_code" => "+238", "idcountry" => "CV"),
            array("country_name" => "Cayman Islands", "dial_code" => "+345", "idcountry" => "KY"),
            array("country_name" => "Central African Republic", "dial_code" => "+236", "idcountry" => "CF"),
            array("country_name" => "Chad", "dial_code" => "+235", "idcountry" => "TD"),
            array("country_name" => "Chile", "dial_code" => "+56", "idcountry" => "CL"),
            array("country_name" => "People's Republic of China", "dial_code" => "+86", "idcountry" => "CN"),
            array("country_name" => "Christmas Island", "dial_code" => "+61", "idcountry" => "CX"),
            array("country_name" => "Cocos (Keeling) Islands", "dial_code" => "+61", "idcountry" => "CC"),
            array("country_name" => "Colombia", "dial_code" => "+57", "idcountry" => "CO"),
            array("country_name" => "Comoros", "dial_code" => "+269", "idcountry" => "KM"),
            array("country_name" => "Congo", "dial_code" => "+242", "idcountry" => "CG"),
            array("country_name" => "Congo, The Democratic Republic of the Congo", "dial_code" => "+243", "idcountry" => "CD"),
            array("country_name" => "Cook Islands", "dial_code" => "+682", "idcountry" => "CK"),
            array("country_name" => "Costa Rica", "dial_code" => "+506", "idcountry" => "CR"),
            array("country_name" => "Cote d'Ivoire", "dial_code" => "+225", "idcountry" => "CI"),
            array("country_name" => "Croatia", "dial_code" => "+385", "idcountry" => "HR"),
            array("country_name" => "Cuba", "dial_code" => "+53", "idcountry" => "CU"),
            array("country_name" => "Cyprus", "dial_code" => "+357", "idcountry" => "CY"),
            array("country_name" => "Czech Republic", "dial_code" => "+420", "idcountry" => "CZ"),
            array("country_name" => "Denmark", "dial_code" => "+45", "idcountry" => "DK"),
            array("country_name" => "Djibouti", "dial_code" => "+253", "idcountry" => "DJ"),
            array("country_name" => "Dominica", "dial_code" => "+1767", "idcountry" => "DM"),
            array("country_name" => "Dominican Republic", "dial_code" => "+1849", "idcountry" => "DO"),
            array("country_name" => "Ecuador", "dial_code" => "+593", "idcountry" => "EC"),
            array("country_name" => "Egypt", "dial_code" => "+20", "idcountry" => "EG"),
            array("country_name" => "El Salvador", "dial_code" => "+503", "idcountry" => "SV"),
            array("country_name" => "Equatorial Guinea", "dial_code" => "+240", "idcountry" => "GQ"),
            array("country_name" => "Eritrea", "dial_code" => "+291", "idcountry" => "ER"),
            array("country_name" => "Estonia", "dial_code" => "+372", "idcountry" => "EE"),
            array("country_name" => "Ethiopia", "dial_code" => "+251", "idcountry" => "ET"),
            array("country_name" => "Falkland Islands (Malvinas)", "dial_code" => "+500", "idcountry" => "FK"),
            array("country_name" => "Faroe Islands", "dial_code" => "+298", "idcountry" => "FO"),
            array("country_name" => "Fiji", "dial_code" => "+679", "idcountry" => "FJ"),
            array("country_name" => "Finland", "dial_code" => "+358", "idcountry" => "FI"),
            array("country_name" => "France", "dial_code" => "+33", "idcountry" => "FR"),
            array("country_name" => "French Guiana", "dial_code" => "+594", "idcountry" => "GF"),
            array("country_name" => "French Polynesia", "dial_code" => "+689", "idcountry" => "PF"),
            array("country_name" => "Gabon", "dial_code" => "+241", "idcountry" => "GA"),
            array("country_name" => "Gambia", "dial_code" => "+220", "idcountry" => "GM"),
            array("country_name" => "Georgia", "dial_code" => "+995", "idcountry" => "GE"),
            array("country_name" => "Germany", "dial_code" => "+49", "idcountry" => "DE"),
            array("country_name" => "Ghana", "dial_code" => "+233", "idcountry" => "GH"),
            array("country_name" => "Gibraltar", "dial_code" => "+350", "idcountry" => "GI"),
            array("country_name" => "Greece", "dial_code" => "+30", "idcountry" => "GR"),
            array("country_name" => "Greenland", "dial_code" => "+299", "idcountry" => "GL"),
            array("country_name" => "Grenada", "dial_code" => "+1473", "idcountry" => "GD"),
            array("country_name" => "Guadeloupe", "dial_code" => "+590", "idcountry" => "GP"),
            array("country_name" => "Guam", "dial_code" => "+1671", "idcountry" => "GU"),
            array("country_name" => "Guatemala", "dial_code" => "+502", "idcountry" => "GT"),
            array("country_name" => "Guernsey", "dial_code" => "+44", "idcountry" => "GG"),
            array("country_name" => "Guinea", "dial_code" => "+224", "idcountry" => "GN"),
            array("country_name" => "Guinea-Bissau", "dial_code" => "+245", "idcountry" => "GW"),
            array("country_name" => "Guyana", "dial_code" => "+595", "idcountry" => "GY"),
            array("country_name" => "Haiti", "dial_code" => "+509", "idcountry" => "HT"),
            array("country_name" => "Holy See (Vatican City State)", "dial_code" => "+379", "idcountry" => "VA"),
            array("country_name" => "Honduras", "dial_code" => "+504", "idcountry" => "HN"),
            array("country_name" => "Hong Kong", "dial_code" => "+852", "idcountry" => "HK"),
            array("country_name" => "Hungary", "dial_code" => "+36", "idcountry" => "HU"),
            array("country_name" => "Iceland", "dial_code" => "+354", "idcountry" => "IS"),
            array("country_name" => "India", "dial_code" => "+91", "idcountry" => "IN"),
            array("country_name" => "Indonesia", "dial_code" => "+62", "idcountry" => "ID"),
            array("country_name" => "Iran, Islamic Republic of Persian Gulf", "dial_code" => "+98", "idcountry" => "IR"),
            array("country_name" => "Iraq", "dial_code" => "+964", "idcountry" => "IQ"),
            array("country_name" => "Ireland", "dial_code" => "+353", "idcountry" => "IE"),
            array("country_name" => "Isle of Man", "dial_code" => "+44", "idcountry" => "IM"),
            array("country_name" => "Israel", "dial_code" => "+972", "idcountry" => "IL"),
            array("country_name" => "Italy", "dial_code" => "+39", "idcountry" => "IT"),
            array("country_name" => "Jamaica", "dial_code" => "+1876", "idcountry" => "JM"),
            array("country_name" => "Japan", "dial_code" => "+81", "idcountry" => "JP"),
            array("country_name" => "Jersey", "dial_code" => "+44", "idcountry" => "JE"),
            array("country_name" => "Jordan", "dial_code" => "+962", "idcountry" => "JO"),
            array("country_name" => "Kazakhstan", "dial_code" => "+77", "idcountry" => "KZ"),
            array("country_name" => "Kenya", "dial_code" => "+254", "idcountry" => "KE"),
            array("country_name" => "Kiribati", "dial_code" => "+686", "idcountry" => "KI"),
            array("country_name" => "Korea, Democratic People's Republic of Korea", "dial_code" => "+850", "idcountry" => "KP"),
            array("country_name" => "Korea, Republic of South Korea", "dial_code" => "+82", "idcountry" => "KR"),
            array("country_name" => "Kuwait", "dial_code" => "+965", "idcountry" => "KW"),
            array("country_name" => "Kyrgyzstan", "dial_code" => "+996", "idcountry" => "KG"),
            array("country_name" => "Laos", "dial_code" => "+856", "idcountry" => "LA"),
            array("country_name" => "Latvia", "dial_code" => "+371", "idcountry" => "LV"),
            array("country_name" => "Lebanon", "dial_code" => "+961", "idcountry" => "LB"),
            array("country_name" => "Lesotho", "dial_code" => "+266", "idcountry" => "LS"),
            array("country_name" => "Liberia", "dial_code" => "+231", "idcountry" => "LR"),
            array("country_name" => "Libyan Arab Jamahiriya", "dial_code" => "+218", "idcountry" => "LY"),
            array("country_name" => "Liechtenstein", "dial_code" => "+423", "idcountry" => "LI"),
            array("country_name" => "Lithuania", "dial_code" => "+370", "idcountry" => "LT"),
            array("country_name" => "Luxembourg", "dial_code" => "+352", "idcountry" => "LU"),
            array("country_name" => "Macao", "dial_code" => "+853", "idcountry" => "MO"),
            array("country_name" => "Macedonia", "dial_code" => "+389", "idcountry" => "MK"),
            array("country_name" => "Madagascar", "dial_code" => "+261", "idcountry" => "MG"),
            array("country_name" => "Malawi", "dial_code" => "+265", "idcountry" => "MW"),
            array("country_name" => "Malaysia", "dial_code" => "+60", "idcountry" => "MY"),
            array("country_name" => "Maldives", "dial_code" => "+960", "idcountry" => "MV"),
            array("country_name" => "Mali", "dial_code" => "+223", "idcountry" => "ML"),
            array("country_name" => "Malta", "dial_code" => "+356", "idcountry" => "MT"),
            array("country_name" => "Marshall Islands", "dial_code" => "+692", "idcountry" => "MH"),
            array("country_name" => "Martinique", "dial_code" => "+596", "idcountry" => "MQ"),
            array("country_name" => "Mauritania", "dial_code" => "+222", "idcountry" => "MR"),
            array("country_name" => "Mauritius", "dial_code" => "+230", "idcountry" => "MU"),
            array("country_name" => "Mayotte", "dial_code" => "+262", "idcountry" => "YT"),
            array("country_name" => "Mexico", "dial_code" => "+52", "idcountry" => "MX"),
            array("country_name" => "Micronesia, Federated States of Micronesia", "dial_code" => "+691", "idcountry" => "FM"),
            array("country_name" => "Moldova", "dial_code" => "+373", "idcountry" => "MD"),
            array("country_name" => "Monaco", "dial_code" => "+377", "idcountry" => "MC"),
            array("country_name" => "Mongolia", "dial_code" => "+976", "idcountry" => "MN"),
            array("country_name" => "Montenegro", "dial_code" => "+382", "idcountry" => "ME"),
            array("country_name" => "Montserrat", "dial_code" => "+1664", "idcountry" => "MS"),
            array("country_name" => "Morocco", "dial_code" => "+212", "idcountry" => "MA"),
            array("country_name" => "Mozambique", "dial_code" => "+258", "idcountry" => "MZ"),
            array("country_name" => "Myanmar", "dial_code" => "+95", "idcountry" => "MM"),
            array("country_name" => "Namibia", "dial_code" => "+264", "idcountry" => "NA"),
            array("country_name" => "Nauru", "dial_code" => "+674", "idcountry" => "NR"),
            array("country_name" => "Nepal", "dial_code" => "+977", "idcountry" => "NP"),
            array("country_name" => "Netherlands", "dial_code" => "+31", "idcountry" => "NL"),
            array("country_name" => "Netherlands Antilles", "dial_code" => "+599", "idcountry" => "AN"),
            array("country_name" => "New Caledonia", "dial_code" => "+687", "idcountry" => "NC"),
            array("country_name" => "New Zealand", "dial_code" => "+64", "idcountry" => "NZ"),
            array("country_name" => "Nicaragua", "dial_code" => "+505", "idcountry" => "NI"),
            array("country_name" => "Niger", "dial_code" => "+227", "idcountry" => "NE"),
            array("country_name" => "Nigeria", "dial_code" => "+234", "idcountry" => "NG"),
            array("country_name" => "Niue", "dial_code" => "+683", "idcountry" => "NU"),
            array("country_name" => "Norfolk Island", "dial_code" => "+672", "idcountry" => "NF"),
            array("country_name" => "Northern Mariana Islands", "dial_code" => "+1670", "idcountry" => "MP"),
            array("country_name" => "Norway", "dial_code" => "+47", "idcountry" => "NO"),
            array("country_name" => "Oman", "dial_code" => "+968", "idcountry" => "OM"),
            array("country_name" => "Pakistan", "dial_code" => "+92", "idcountry" => "PK"),
            array("country_name" => "Palau", "dial_code" => "+680", "idcountry" => "PW"),
            array("country_name" => "Palestinian Territory, Occupied", "dial_code" => "+970", "idcountry" => "PS"),
            array("country_name" => "Panama", "dial_code" => "+507", "idcountry" => "PA"),
            array("country_name" => "Papua New Guinea", "dial_code" => "+675", "idcountry" => "PG"),
            array("country_name" => "Paraguay", "dial_code" => "+595", "idcountry" => "PY"),
            array("country_name" => "Peru", "dial_code" => "+51", "idcountry" => "PE"),
            array("country_name" => "Philippines", "dial_code" => "+63", "idcountry" => "PH"),
            array("country_name" => "Pitcairn", "dial_code" => "+872", "idcountry" => "PN"),
            array("country_name" => "Poland", "dial_code" => "+48", "idcountry" => "PL"),
            array("country_name" => "Portugal", "dial_code" => "+351", "idcountry" => "PT"),
            array("country_name" => "Puerto Rico", "dial_code" => "+1939", "idcountry" => "PR"),
            array("country_name" => "Qatar", "dial_code" => "+974", "idcountry" => "QA"),
            array("country_name" => "Romania", "dial_code" => "+40", "idcountry" => "RO"),
            array("country_name" => "Russia", "dial_code" => "+7", "idcountry" => "RU"),
            array("country_name" => "Rwanda", "dial_code" => "+250", "idcountry" => "RW"),
            array("country_name" => "Reunion", "dial_code" => "+262", "idcountry" => "RE"),
            array("country_name" => "Saint Barthelemy", "dial_code" => "+590", "idcountry" => "BL"),
            array("country_name" => "Saint Helena, Ascension and Tristan Da Cunha", "dial_code" => "+290", "idcountry" => "SH"),
            array("country_name" => "Saint Kitts and Nevis", "dial_code" => "+1869", "idcountry" => "KN"),
            array("country_name" => "Saint Lucia", "dial_code" => "+1758", "idcountry" => "LC"),
            array("country_name" => "Saint Martin", "dial_code" => "+590", "idcountry" => "MF"),
            array("country_name" => "Saint Pierre and Miquelon", "dial_code" => "+508", "idcountry" => "PM"),
            array("country_name" => "Saint Vincent and the Grenadines", "dial_code" => "+1784", "idcountry" => "VC"),
            array("country_name" => "Samoa", "dial_code" => "+685", "idcountry" => "WS"),
            array("country_name" => "San Marino", "dial_code" => "+378", "idcountry" => "SM"),
            array("country_name" => "Sao Tome and Principe", "dial_code" => "+239", "idcountry" => "ST"),
            array("country_name" => "Saudi Arabia", "dial_code" => "+966", "idcountry" => "SA"),
            array("country_name" => "Senegal", "dial_code" => "+221", "idcountry" => "SN"),
            array("country_name" => "Serbia", "dial_code" => "+381", "idcountry" => "RS"),
            array("country_name" => "Seychelles", "dial_code" => "+248", "idcountry" => "SC"),
            array("country_name" => "Sierra Leone", "dial_code" => "+232", "idcountry" => "SL"),
            array("country_name" => "Singapore", "dial_code" => "+65", "idcountry" => "SG"),
            array("country_name" => "Slovakia", "dial_code" => "+421", "idcountry" => "SK"),
            array("country_name" => "Slovenia", "dial_code" => "+386", "idcountry" => "SI"),
            array("country_name" => "Solomon Islands", "dial_code" => "+677", "idcountry" => "SB"),
            array("country_name" => "Somalia", "dial_code" => "+252", "idcountry" => "SO"),
            array("country_name" => "South Africa", "dial_code" => "+27", "idcountry" => "ZA"),
            array("country_name" => "South Sudan", "dial_code" => "+211", "idcountry" => "SS"),
            array("country_name" => "South Georgia and the South Sandwich Islands", "dial_code" => "+500", "idcountry" => "GS"),
            array("country_name" => "Spain", "dial_code" => "+34", "idcountry" => "ES"),
            array("country_name" => "Sri Lanka", "dial_code" => "+94", "idcountry" => "LK"),
            array("country_name" => "Sudan", "dial_code" => "+249", "idcountry" => "SD"),
            array("country_name" => "Suriname", "dial_code" => "+597", "idcountry" => "SR"),
            array("country_name" => "Svalbard and Jan Mayen", "dial_code" => "+47", "idcountry" => "SJ"),
            array("country_name" => "Swaziland", "dial_code" => "+268", "idcountry" => "SZ"),
            array("country_name" => "Sweden", "dial_code" => "+46", "idcountry" => "SE"),
            array("country_name" => "Switzerland", "dial_code" => "+41", "idcountry" => "CH"),
            array("country_name" => "Syrian Arab Republic", "dial_code" => "+963", "idcountry" => "SY"),
            array("country_name" => "Taiwan", "dial_code" => "+886", "idcountry" => "TW"),
            array("country_name" => "Tajikistan", "dial_code" => "+992", "idcountry" => "TJ"),
            array("country_name" => "Tanzania, United Republic of Tanzania", "dial_code" => "+255", "idcountry" => "TZ"),
            array("country_name" => "Thailand", "dial_code" => "+66", "idcountry" => "TH"),
            array("country_name" => "Timor-Leste", "dial_code" => "+670", "idcountry" => "TL"),
            array("country_name" => "Togo", "dial_code" => "+228", "idcountry" => "TG"),
            array("country_name" => "Tokelau", "dial_code" => "+690", "idcountry" => "TK"),
            array("country_name" => "Tonga", "dial_code" => "+676", "idcountry" => "TO"),
            array("country_name" => "Trinidad and Tobago", "dial_code" => "+1868", "idcountry" => "TT"),
            array("country_name" => "Tunisia", "dial_code" => "+216", "idcountry" => "TN"),
            array("country_name" => "Turkey", "dial_code" => "+90", "idcountry" => "TR"),
            array("country_name" => "Turkmenistan", "dial_code" => "+993", "idcountry" => "TM"),
            array("country_name" => "Turks and Caicos Islands", "dial_code" => "+1649", "idcountry" => "TC"),
            array("country_name" => "Tuvalu", "dial_code" => "+688", "idcountry" => "TV"),
            array("country_name" => "Uganda", "dial_code" => "+256", "idcountry" => "UG"),
            array("country_name" => "Ukraine", "dial_code" => "+380", "idcountry" => "UA"),
            array("country_name" => "United Arab Emirates", "dial_code" => "+971", "idcountry" => "AE"),
            array("country_name" => "United Kingdom", "dial_code" => "+44", "idcountry" => "GB"),
            array("country_name" => "United States", "dial_code" => "+1", "idcountry" => "US"),
            array("country_name" => "Uruguay", "dial_code" => "+598", "idcountry" => "UY"),
            array("country_name" => "Uzbekistan", "dial_code" => "+998", "idcountry" => "UZ"),
            array("country_name" => "Vanuatu", "dial_code" => "+678", "idcountry" => "VU"),
            array("country_name" => "Venezuela, Bolivarian Republic of Venezuela", "dial_code" => "+58", "idcountry" => "VE"),
            array("country_name" => "Vietnam", "dial_code" => "+84", "idcountry" => "VN"),
            array("country_name" => "Virgin Islands, British", "dial_code" => "+1284", "idcountry" => "VG"),
            array("country_name" => "Virgin Islands, U.S.", "dial_code" => "+1340", "idcountry" => "VI"),
            array("country_name" => "Wallis and Futuna", "dial_code" => "+681", "idcountry" => "WF"),
            array("country_name" => "Yemen", "dial_code" => "+967", "idcountry" => "YE"),
            array("country_name" => "Zambia", "dial_code" => "+260", "idcountry" => "ZM"),
            array("country_name" => "Zimbabwe", "dial_code" => "+263", "idcountry" => "ZW")
        );

        tbcountry::insert($country);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
