<?php

use App\Models\countries;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id('id');
            $table->string('code', 10);
            $table->string('country_name', 100);
            $table->string('dial_code', 10);
        });
        $country = array(
            array("country_name" => "Afghanistan", "dial_code" => "+93", "code" => "AF"),
            array("country_name" => "Aland Islands", "dial_code" => "+358", "code" => "AX"),
            array("country_name" => "Albania", "dial_code" => "+355", "code" => "AL"),
            array("country_name" => "Algeria", "dial_code" => "+213", "code" => "DZ"),
            array("country_name" => "AmericanSamoa", "dial_code" => "+1684", "code" => "AS"),
            array("country_name" => "Andorra", "dial_code" => "+376", "code" => "AD"),
            array("country_name" => "Angola", "dial_code" => "+244", "code" => "AO"),
            array("country_name" => "Anguilla", "dial_code" => "+1264", "code" => "AI"),
            array("country_name" => "Antarctica", "dial_code" => "+672", "code" => "AQ"),
            array("country_name" => "Antigua and Barbuda", "dial_code" => "+1268", "code" => "AG"),
            array("country_name" => "Argentina", "dial_code" => "+54", "code" => "AR"),
            array("country_name" => "Armenia", "dial_code" => "+374", "code" => "AM"),
            array("country_name" => "Aruba", "dial_code" => "+297", "code" => "AW"),
            array("country_name" => "Australia", "dial_code" => "+61", "code" => "AU"),
            array("country_name" => "Austria", "dial_code" => "+43", "code" => "AT"),
            array("country_name" => "Azerbaijan", "dial_code" => "+994", "code" => "AZ"),
            array("country_name" => "Bahamas", "dial_code" => "+1242", "code" => "BS"),
            array("country_name" => "Bahrain", "dial_code" => "+973", "code" => "BH"),
            array("country_name" => "Bangladesh", "dial_code" => "+880", "code" => "BD"),
            array("country_name" => "Barbados", "dial_code" => "+1246", "code" => "BB"),
            array("country_name" => "Belarus", "dial_code" => "+375", "code" => "BY"),
            array("country_name" => "Belgium", "dial_code" => "+32", "code" => "BE"),
            array("country_name" => "Belize", "dial_code" => "+501", "code" => "BZ"),
            array("country_name" => "Benin", "dial_code" => "+229", "code" => "BJ"),
            array("country_name" => "Bermuda", "dial_code" => "+1441", "code" => "BM"),
            array("country_name" => "Bhutan", "dial_code" => "+975", "code" => "BT"),
            array("country_name" => "Bolivia, Plurinational State of", "dial_code" => "+591", "code" => "BO"),
            array("country_name" => "Bosnia and Herzegovina", "dial_code" => "+387", "code" => "BA"),
            array("country_name" => "Botswana", "dial_code" => "+267", "code" => "BW"),
            array("country_name" => "Brazil", "dial_code" => "+55", "code" => "BR"),
            array("country_name" => "British Indian Ocean Territory", "dial_code" => "+246", "code" => "IO"),
            array("country_name" => "Brunei Darussalam", "dial_code" => "+673", "code" => "BN"),
            array("country_name" => "Bulgaria", "dial_code" => "+359", "code" => "BG"),
            array("country_name" => "Burkina Faso", "dial_code" => "+226", "code" => "BF"),
            array("country_name" => "Burundi", "dial_code" => "+257", "code" => "BI"),
            array("country_name" => "Cambodia", "dial_code" => "+855", "code" => "KH"),
            array("country_name" => "Cameroon", "dial_code" => "+237", "code" => "CM"),
            array("country_name" => "Canada", "dial_code" => "+1", "code" => "CA"),
            array("country_name" => "Cape Verde", "dial_code" => "+238", "code" => "CV"),
            array("country_name" => "Cayman Islands", "dial_code" => "+345", "code" => "KY"),
            array("country_name" => "Central African Republic", "dial_code" => "+236", "code" => "CF"),
            array("country_name" => "Chad", "dial_code" => "+235", "code" => "TD"),
            array("country_name" => "Chile", "dial_code" => "+56", "code" => "CL"),
            array("country_name" => "People's Republic of China", "dial_code" => "+86", "code" => "CN"),
            array("country_name" => "Christmas Island", "dial_code" => "+61", "code" => "CX"),
            array("country_name" => "Cocos (Keeling) Islands", "dial_code" => "+61", "code" => "CC"),
            array("country_name" => "Colombia", "dial_code" => "+57", "code" => "CO"),
            array("country_name" => "Comoros", "dial_code" => "+269", "code" => "KM"),
            array("country_name" => "Congo", "dial_code" => "+242", "code" => "CG"),
            array("country_name" => "Congo, The Democratic Republic of the Congo", "dial_code" => "+243", "code" => "CD"),
            array("country_name" => "Cook Islands", "dial_code" => "+682", "code" => "CK"),
            array("country_name" => "Costa Rica", "dial_code" => "+506", "code" => "CR"),
            array("country_name" => "Cote d'Ivoire", "dial_code" => "+225", "code" => "CI"),
            array("country_name" => "Croatia", "dial_code" => "+385", "code" => "HR"),
            array("country_name" => "Cuba", "dial_code" => "+53", "code" => "CU"),
            array("country_name" => "Cyprus", "dial_code" => "+357", "code" => "CY"),
            array("country_name" => "Czech Republic", "dial_code" => "+420", "code" => "CZ"),
            array("country_name" => "Denmark", "dial_code" => "+45", "code" => "DK"),
            array("country_name" => "Djibouti", "dial_code" => "+253", "code" => "DJ"),
            array("country_name" => "Dominica", "dial_code" => "+1767", "code" => "DM"),
            array("country_name" => "Dominican Republic", "dial_code" => "+1849", "code" => "DO"),
            array("country_name" => "Ecuador", "dial_code" => "+593", "code" => "EC"),
            array("country_name" => "Egypt", "dial_code" => "+20", "code" => "EG"),
            array("country_name" => "El Salvador", "dial_code" => "+503", "code" => "SV"),
            array("country_name" => "Equatorial Guinea", "dial_code" => "+240", "code" => "GQ"),
            array("country_name" => "Eritrea", "dial_code" => "+291", "code" => "ER"),
            array("country_name" => "Estonia", "dial_code" => "+372", "code" => "EE"),
            array("country_name" => "Ethiopia", "dial_code" => "+251", "code" => "ET"),
            array("country_name" => "Falkland Islands (Malvinas)", "dial_code" => "+500", "code" => "FK"),
            array("country_name" => "Faroe Islands", "dial_code" => "+298", "code" => "FO"),
            array("country_name" => "Fiji", "dial_code" => "+679", "code" => "FJ"),
            array("country_name" => "Finland", "dial_code" => "+358", "code" => "FI"),
            array("country_name" => "France", "dial_code" => "+33", "code" => "FR"),
            array("country_name" => "French Guiana", "dial_code" => "+594", "code" => "GF"),
            array("country_name" => "French Polynesia", "dial_code" => "+689", "code" => "PF"),
            array("country_name" => "Gabon", "dial_code" => "+241", "code" => "GA"),
            array("country_name" => "Gambia", "dial_code" => "+220", "code" => "GM"),
            array("country_name" => "Georgia", "dial_code" => "+995", "code" => "GE"),
            array("country_name" => "Germany", "dial_code" => "+49", "code" => "DE"),
            array("country_name" => "Ghana", "dial_code" => "+233", "code" => "GH"),
            array("country_name" => "Gibraltar", "dial_code" => "+350", "code" => "GI"),
            array("country_name" => "Greece", "dial_code" => "+30", "code" => "GR"),
            array("country_name" => "Greenland", "dial_code" => "+299", "code" => "GL"),
            array("country_name" => "Grenada", "dial_code" => "+1473", "code" => "GD"),
            array("country_name" => "Guadeloupe", "dial_code" => "+590", "code" => "GP"),
            array("country_name" => "Guam", "dial_code" => "+1671", "code" => "GU"),
            array("country_name" => "Guatemala", "dial_code" => "+502", "code" => "GT"),
            array("country_name" => "Guernsey", "dial_code" => "+44", "code" => "GG"),
            array("country_name" => "Guinea", "dial_code" => "+224", "code" => "GN"),
            array("country_name" => "Guinea-Bissau", "dial_code" => "+245", "code" => "GW"),
            array("country_name" => "Guyana", "dial_code" => "+595", "code" => "GY"),
            array("country_name" => "Haiti", "dial_code" => "+509", "code" => "HT"),
            array("country_name" => "Holy See (Vatican City State)", "dial_code" => "+379", "code" => "VA"),
            array("country_name" => "Honduras", "dial_code" => "+504", "code" => "HN"),
            array("country_name" => "Hong Kong", "dial_code" => "+852", "code" => "HK"),
            array("country_name" => "Hungary", "dial_code" => "+36", "code" => "HU"),
            array("country_name" => "Iceland", "dial_code" => "+354", "code" => "IS"),
            array("country_name" => "India", "dial_code" => "+91", "code" => "IN"),
            array("country_name" => "Indonesia", "dial_code" => "+62", "code" => "ID"),
            array("country_name" => "Iran, Islamic Republic of Persian Gulf", "dial_code" => "+98", "code" => "IR"),
            array("country_name" => "Iraq", "dial_code" => "+964", "code" => "IQ"),
            array("country_name" => "Ireland", "dial_code" => "+353", "code" => "IE"),
            array("country_name" => "Isle of Man", "dial_code" => "+44", "code" => "IM"),
            array("country_name" => "Israel", "dial_code" => "+972", "code" => "IL"),
            array("country_name" => "Italy", "dial_code" => "+39", "code" => "IT"),
            array("country_name" => "Jamaica", "dial_code" => "+1876", "code" => "JM"),
            array("country_name" => "Japan", "dial_code" => "+81", "code" => "JP"),
            array("country_name" => "Jersey", "dial_code" => "+44", "code" => "JE"),
            array("country_name" => "Jordan", "dial_code" => "+962", "code" => "JO"),
            array("country_name" => "Kazakhstan", "dial_code" => "+77", "code" => "KZ"),
            array("country_name" => "Kenya", "dial_code" => "+254", "code" => "KE"),
            array("country_name" => "Kiribati", "dial_code" => "+686", "code" => "KI"),
            array("country_name" => "Korea, Democratic People's Republic of Korea", "dial_code" => "+850", "code" => "KP"),
            array("country_name" => "Korea, Republic of South Korea", "dial_code" => "+82", "code" => "KR"),
            array("country_name" => "Kuwait", "dial_code" => "+965", "code" => "KW"),
            array("country_name" => "Kyrgyzstan", "dial_code" => "+996", "code" => "KG"),
            array("country_name" => "Laos", "dial_code" => "+856", "code" => "LA"),
            array("country_name" => "Latvia", "dial_code" => "+371", "code" => "LV"),
            array("country_name" => "Lebanon", "dial_code" => "+961", "code" => "LB"),
            array("country_name" => "Lesotho", "dial_code" => "+266", "code" => "LS"),
            array("country_name" => "Liberia", "dial_code" => "+231", "code" => "LR"),
            array("country_name" => "Libyan Arab Jamahiriya", "dial_code" => "+218", "code" => "LY"),
            array("country_name" => "Liechtenstein", "dial_code" => "+423", "code" => "LI"),
            array("country_name" => "Lithuania", "dial_code" => "+370", "code" => "LT"),
            array("country_name" => "Luxembourg", "dial_code" => "+352", "code" => "LU"),
            array("country_name" => "Macao", "dial_code" => "+853", "code" => "MO"),
            array("country_name" => "Macedonia", "dial_code" => "+389", "code" => "MK"),
            array("country_name" => "Madagascar", "dial_code" => "+261", "code" => "MG"),
            array("country_name" => "Malawi", "dial_code" => "+265", "code" => "MW"),
            array("country_name" => "Malaysia", "dial_code" => "+60", "code" => "MY"),
            array("country_name" => "Maldives", "dial_code" => "+960", "code" => "MV"),
            array("country_name" => "Mali", "dial_code" => "+223", "code" => "ML"),
            array("country_name" => "Malta", "dial_code" => "+356", "code" => "MT"),
            array("country_name" => "Marshall Islands", "dial_code" => "+692", "code" => "MH"),
            array("country_name" => "Martinique", "dial_code" => "+596", "code" => "MQ"),
            array("country_name" => "Mauritania", "dial_code" => "+222", "code" => "MR"),
            array("country_name" => "Mauritius", "dial_code" => "+230", "code" => "MU"),
            array("country_name" => "Mayotte", "dial_code" => "+262", "code" => "YT"),
            array("country_name" => "Mexico", "dial_code" => "+52", "code" => "MX"),
            array("country_name" => "Micronesia, Federated States of Micronesia", "dial_code" => "+691", "code" => "FM"),
            array("country_name" => "Moldova", "dial_code" => "+373", "code" => "MD"),
            array("country_name" => "Monaco", "dial_code" => "+377", "code" => "MC"),
            array("country_name" => "Mongolia", "dial_code" => "+976", "code" => "MN"),
            array("country_name" => "Montenegro", "dial_code" => "+382", "code" => "ME"),
            array("country_name" => "Montserrat", "dial_code" => "+1664", "code" => "MS"),
            array("country_name" => "Morocco", "dial_code" => "+212", "code" => "MA"),
            array("country_name" => "Mozambique", "dial_code" => "+258", "code" => "MZ"),
            array("country_name" => "Myanmar", "dial_code" => "+95", "code" => "MM"),
            array("country_name" => "Namibia", "dial_code" => "+264", "code" => "NA"),
            array("country_name" => "Nauru", "dial_code" => "+674", "code" => "NR"),
            array("country_name" => "Nepal", "dial_code" => "+977", "code" => "NP"),
            array("country_name" => "Netherlands", "dial_code" => "+31", "code" => "NL"),
            array("country_name" => "Netherlands Antilles", "dial_code" => "+599", "code" => "AN"),
            array("country_name" => "New Caledonia", "dial_code" => "+687", "code" => "NC"),
            array("country_name" => "New Zealand", "dial_code" => "+64", "code" => "NZ"),
            array("country_name" => "Nicaragua", "dial_code" => "+505", "code" => "NI"),
            array("country_name" => "Niger", "dial_code" => "+227", "code" => "NE"),
            array("country_name" => "Nigeria", "dial_code" => "+234", "code" => "NG"),
            array("country_name" => "Niue", "dial_code" => "+683", "code" => "NU"),
            array("country_name" => "Norfolk Island", "dial_code" => "+672", "code" => "NF"),
            array("country_name" => "Northern Mariana Islands", "dial_code" => "+1670", "code" => "MP"),
            array("country_name" => "Norway", "dial_code" => "+47", "code" => "NO"),
            array("country_name" => "Oman", "dial_code" => "+968", "code" => "OM"),
            array("country_name" => "Pakistan", "dial_code" => "+92", "code" => "PK"),
            array("country_name" => "Palau", "dial_code" => "+680", "code" => "PW"),
            array("country_name" => "Palestinian Territory, Occupied", "dial_code" => "+970", "code" => "PS"),
            array("country_name" => "Panama", "dial_code" => "+507", "code" => "PA"),
            array("country_name" => "Papua New Guinea", "dial_code" => "+675", "code" => "PG"),
            array("country_name" => "Paraguay", "dial_code" => "+595", "code" => "PY"),
            array("country_name" => "Peru", "dial_code" => "+51", "code" => "PE"),
            array("country_name" => "Philippines", "dial_code" => "+63", "code" => "PH"),
            array("country_name" => "Pitcairn", "dial_code" => "+872", "code" => "PN"),
            array("country_name" => "Poland", "dial_code" => "+48", "code" => "PL"),
            array("country_name" => "Portugal", "dial_code" => "+351", "code" => "PT"),
            array("country_name" => "Puerto Rico", "dial_code" => "+1939", "code" => "PR"),
            array("country_name" => "Qatar", "dial_code" => "+974", "code" => "QA"),
            array("country_name" => "Romania", "dial_code" => "+40", "code" => "RO"),
            array("country_name" => "Russia", "dial_code" => "+7", "code" => "RU"),
            array("country_name" => "Rwanda", "dial_code" => "+250", "code" => "RW"),
            array("country_name" => "Reunion", "dial_code" => "+262", "code" => "RE"),
            array("country_name" => "Saint Barthelemy", "dial_code" => "+590", "code" => "BL"),
            array("country_name" => "Saint Helena, Ascension and Tristan Da Cunha", "dial_code" => "+290", "code" => "SH"),
            array("country_name" => "Saint Kitts and Nevis", "dial_code" => "+1869", "code" => "KN"),
            array("country_name" => "Saint Lucia", "dial_code" => "+1758", "code" => "LC"),
            array("country_name" => "Saint Martin", "dial_code" => "+590", "code" => "MF"),
            array("country_name" => "Saint Pierre and Miquelon", "dial_code" => "+508", "code" => "PM"),
            array("country_name" => "Saint Vincent and the Grenadines", "dial_code" => "+1784", "code" => "VC"),
            array("country_name" => "Samoa", "dial_code" => "+685", "code" => "WS"),
            array("country_name" => "San Marino", "dial_code" => "+378", "code" => "SM"),
            array("country_name" => "Sao Tome and Principe", "dial_code" => "+239", "code" => "ST"),
            array("country_name" => "Saudi Arabia", "dial_code" => "+966", "code" => "SA"),
            array("country_name" => "Senegal", "dial_code" => "+221", "code" => "SN"),
            array("country_name" => "Serbia", "dial_code" => "+381", "code" => "RS"),
            array("country_name" => "Seychelles", "dial_code" => "+248", "code" => "SC"),
            array("country_name" => "Sierra Leone", "dial_code" => "+232", "code" => "SL"),
            array("country_name" => "Singapore", "dial_code" => "+65", "code" => "SG"),
            array("country_name" => "Slovakia", "dial_code" => "+421", "code" => "SK"),
            array("country_name" => "Slovenia", "dial_code" => "+386", "code" => "SI"),
            array("country_name" => "Solomon Islands", "dial_code" => "+677", "code" => "SB"),
            array("country_name" => "Somalia", "dial_code" => "+252", "code" => "SO"),
            array("country_name" => "South Africa", "dial_code" => "+27", "code" => "ZA"),
            array("country_name" => "South Sudan", "dial_code" => "+211", "code" => "SS"),
            array("country_name" => "South Georgia and the South Sandwich Islands", "dial_code" => "+500", "code" => "GS"),
            array("country_name" => "Spain", "dial_code" => "+34", "code" => "ES"),
            array("country_name" => "Sri Lanka", "dial_code" => "+94", "code" => "LK"),
            array("country_name" => "Sudan", "dial_code" => "+249", "code" => "SD"),
            array("country_name" => "Suriname", "dial_code" => "+597", "code" => "SR"),
            array("country_name" => "Svalbard and Jan Mayen", "dial_code" => "+47", "code" => "SJ"),
            array("country_name" => "Swaziland", "dial_code" => "+268", "code" => "SZ"),
            array("country_name" => "Sweden", "dial_code" => "+46", "code" => "SE"),
            array("country_name" => "Switzerland", "dial_code" => "+41", "code" => "CH"),
            array("country_name" => "Syrian Arab Republic", "dial_code" => "+963", "code" => "SY"),
            array("country_name" => "Taiwan", "dial_code" => "+886", "code" => "TW"),
            array("country_name" => "Tajikistan", "dial_code" => "+992", "code" => "TJ"),
            array("country_name" => "Tanzania, United Republic of Tanzania", "dial_code" => "+255", "code" => "TZ"),
            array("country_name" => "Thailand", "dial_code" => "+66", "code" => "TH"),
            array("country_name" => "Timor-Leste", "dial_code" => "+670", "code" => "TL"),
            array("country_name" => "Togo", "dial_code" => "+228", "code" => "TG"),
            array("country_name" => "Tokelau", "dial_code" => "+690", "code" => "TK"),
            array("country_name" => "Tonga", "dial_code" => "+676", "code" => "TO"),
            array("country_name" => "Trinidad and Tobago", "dial_code" => "+1868", "code" => "TT"),
            array("country_name" => "Tunisia", "dial_code" => "+216", "code" => "TN"),
            array("country_name" => "Turkey", "dial_code" => "+90", "code" => "TR"),
            array("country_name" => "Turkmenistan", "dial_code" => "+993", "code" => "TM"),
            array("country_name" => "Turks and Caicos Islands", "dial_code" => "+1649", "code" => "TC"),
            array("country_name" => "Tuvalu", "dial_code" => "+688", "code" => "TV"),
            array("country_name" => "Uganda", "dial_code" => "+256", "code" => "UG"),
            array("country_name" => "Ukraine", "dial_code" => "+380", "code" => "UA"),
            array("country_name" => "United Arab Emirates", "dial_code" => "+971", "code" => "AE"),
            array("country_name" => "United Kingdom", "dial_code" => "+44", "code" => "GB"),
            array("country_name" => "United States", "dial_code" => "+1", "code" => "US"),
            array("country_name" => "Uruguay", "dial_code" => "+598", "code" => "UY"),
            array("country_name" => "Uzbekistan", "dial_code" => "+998", "code" => "UZ"),
            array("country_name" => "Vanuatu", "dial_code" => "+678", "code" => "VU"),
            array("country_name" => "Venezuela, Bolivarian Republic of Venezuela", "dial_code" => "+58", "code" => "VE"),
            array("country_name" => "Vietnam", "dial_code" => "+84", "code" => "VN"),
            array("country_name" => "Virgin Islands, British", "dial_code" => "+1284", "code" => "VG"),
            array("country_name" => "Virgin Islands, U.S.", "dial_code" => "+1340", "code" => "VI"),
            array("country_name" => "Wallis and Futuna", "dial_code" => "+681", "code" => "WF"),
            array("country_name" => "Yemen", "dial_code" => "+967", "code" => "YE"),
            array("country_name" => "Zambia", "dial_code" => "+260", "code" => "ZM"),
            array("country_name" => "Zimbabwe", "dial_code" => "+263", "code" => "ZW")
        );

        countries::insert($country);
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
